micronaut:
  metrics:
    export:
      stackdriver:
        enabled: true
        projectId: ${STACKDRIVER_PROJECT_ID}
        step: PT1M
    enabled: true
  application:
    server:
      port: ${PORT}
  http:
    client:
      read-timeout: 500s
      pool:
        enabled: true
        max-connections: 50
      event-loop-group: client
  executors:
    io:
      type: fixed
      n-threads: 200
  netty:
    event-loops:
      client:
        num-threads: 20
        prefer-native-transport: true

crawl:
  metadata:
    frequency: 60
  channels:
    parallelism: 50
functions:
  update_handler: 'https://europe-west1-enduring-button-90012.cloudfunctions.net/updatehandler'
  url: 'https://europe-west1-enduring-button-90012.cloudfunctions.net/getchannelvideos'
datasources:
  default:
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    maximum-pool-size: 20
flyway:
  datasources:
    default:
      enabled: true
logger:
  levels:
    palantir: DEBUG
netty:
  default:
    allocator:
      max-order: 3
tracing:
  zipkin:
    enabled: true